// swift-tools-version: 5.6

// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import PackageDescription

let package = Package(
    name: "YassirKeys",
    platforms: [
        .macOS(.v11),
        .iOS(.v11),
        .tvOS(.v11),
        .watchOS(.v4),
    ],
    products: [
        .library(
            name: "YassirKeys",
            targets: ["YassirKeys"]
        ),
    ],
    dependencies: [
        .package(name: "YassirKeysInterfaces", path: "../YassirKeysInterfaces"),
    ],
    targets: [
        .target(
            name: "YassirKeys",
            dependencies: ["YassirKeysInterfaces"],
            path: "Sources"
        ),
        .testTarget(
            name: "YassirKeysTests",
            dependencies: ["YassirKeys"],
            path: "Tests"
        ),
    ]
)
